const pool = require('./db');
const nodemailer = require('nodemailer');
require('dotenv').config();

async function simulatePriceUpdate() {
    console.log("🎯 PriceBuddy Demo Script: Simulating Price Fluctuation...");

    try {
        // 1. Fetch a product to update (Preferably one with a target_price set)
        const [rows] = await pool.query(`
            SELECT 
                s.id as source_id, s.last_price, s.target_price, p.name, u.email as user_email, u.id as user_id
            FROM product_sources s
            JOIN products p ON s.product_id = p.id
            JOIN users u ON p.user_id = u.id
            ORDER BY s.id DESC
            LIMIT 1
        `);

        if (rows.length === 0) {
            console.log("❌ No products found in database to simulate.");
            return;
        }

        const product = rows[0];
        const oldPrice = parseFloat(product.last_price || 0);

        // 2. Simulate a 10% price drop to trigger alerts
        // If price is 0 (syncing), let's set a baseline
        const basePrice = oldPrice > 0 ? oldPrice : 50000;
        const newPrice = parseFloat((basePrice * 0.9).toFixed(2));

        console.log(`📦 Product: ${product.name}`);
        console.log(`💰 Old Price: ₹${oldPrice.toLocaleString()}`);
        console.log(`📉 New Price (Simulated): ₹${newPrice.toLocaleString()}`);

        // 3. Update Database
        await pool.query('UPDATE product_sources SET last_price = ? WHERE id = ?', [newPrice, product.source_id]);
        await pool.query('INSERT INTO price_history (product_source_id, price) VALUES (?, ?)', [product.source_id, newPrice]);

        console.log("✅ Database updated successfully.");

        // 4. Send Email Alert (The Full Demo Loop)
        const targetPrice = product.target_price ? parseFloat(product.target_price) : null;
        if (newPrice < oldPrice && (!targetPrice || newPrice <= targetPrice)) {
            console.log("📧 Conditions met! Sending demo email alert...");

            const transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                    user: process.env.EMAIL_USER,
                    pass: process.env.EMAIL_PASS
                }
            });

            const mailOptions = {
                from: `"PriceBuddy Demo" <${process.env.EMAIL_USER}>`,
                to: product.user_email,
                subject: `📉 DEMO ALERT: ${product.name} Price Drop!`,
                html: `
                    <div style="font-family: sans-serif; padding: 20px; border: 1px solid #00E5FF; border-radius: 10px;">
                        <h1 style="color: #00E5FF;">DEMO PRICE DROP</h1>
                        <p>This is a simulated price drop for your demo.</p>
                        <p><strong>Product:</strong> ${product.name}</p>
                        <p><strong>New Price:</strong> <span style="color: #16a34a; font-size: 20px;">₹${newPrice.toLocaleString()}</span></p>
                        <p><strong>Previous:</strong> ₹${oldPrice.toLocaleString()}</p>
                        <p style="margin-top: 20px; font-size: 12px; color: #666;">Generated by the PriceBuddy Demo Script.</p>
                    </div>
                `
            };

            await transporter.sendMail(mailOptions);
            console.log(`🚀 Demo email sent to ${product.user_email}`);
        }

        console.log("\n✨ Demo complete! Refresh your dashboard now to see the changes.");

    } catch (error) {
        console.error("❌ Demo Error:", error.message);
    } finally {
        process.exit();
    }
}

simulatePriceUpdate();
