const pool = require('./db');
const nodemailer = require('nodemailer');
require('dotenv').config();

async function simulatePriceUpdate() {
    const targetProductId = process.argv[2]; // e.g. node simulate_demo.js 5

    console.log(`🎯 PriceBuddy Demo Script: ${targetProductId ? `Targeting Product ID ${targetProductId}` : 'Simulating Latest Product'}...`);

    try {
        let query = `
            SELECT 
                s.id as source_id, s.last_price, s.target_price, p.name, u.email as user_email, u.id as user_id, p.id as product_id, u.notifications_active
            FROM product_sources s
            JOIN products p ON s.product_id = p.id
            JOIN users u ON p.user_id = u.id
        `;
        let params = [];

        if (targetProductId) {
            query += " WHERE p.id = ? ";
            params.push(targetProductId);
        } else {
            query += " ORDER BY s.id DESC LIMIT 1 ";
        }

        const [rows] = await pool.query(query, params);

        if (rows.length === 0) {
            console.log("❌ No products found in database to simulate.");
            return;
        }

        const product = rows[0];
        const oldPrice = parseFloat(product.last_price || 0);

        // 2. Simulate a 10% price drop to trigger alerts
        // If price is 0 (syncing), let's set a baseline
        const basePrice = oldPrice > 0 ? oldPrice : 50000;
        const newPrice = parseFloat((basePrice * 0.9).toFixed(2));

        console.log(`📦 Product: ${product.name}`);
        console.log(`💰 Old Price: ₹${oldPrice.toLocaleString()}`);
        console.log(`📉 New Price (Simulated): ₹${newPrice.toLocaleString()}`);

        // 3. Update Database
        await pool.query('UPDATE product_sources SET last_price = ? WHERE id = ?', [newPrice, product.source_id]);

        // 3.1 Demo Logic: Ensure we have at least 2 points to show a curve
        const [historyCheck] = await pool.query('SELECT count(*) as count FROM price_history WHERE product_source_id = ?', [product.source_id]);

        if (historyCheck[0].count === 0 && oldPrice > 0) {
            // Insert the OLD price as a point 15 minutes ago so the chart has a starting point
            const fifteenMinsAgo = new Date(Date.now() - 15 * 60 * 1000);
            await pool.query('INSERT INTO price_history (product_source_id, price, scraped_at) VALUES (?, ?, ?)', [product.source_id, oldPrice, fifteenMinsAgo]);
        }

        // Insert the NEW price drop point
        await pool.query('INSERT INTO price_history (product_source_id, price, scraped_at) VALUES (?, ?, ?)', [product.source_id, newPrice, new Date()]);

        console.log("✅ Database updated with trend points.");

        // 4. Send Email Alert (The Full Demo Loop)
        const targetPrice = product.target_price ? parseFloat(product.target_price) : null;
        if (newPrice < oldPrice && (!targetPrice || newPrice <= targetPrice) && product.notifications_active) {
            console.log("📧 Conditions met! Sending demo email alert...");

            const transporter = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                    user: process.env.EMAIL_USER,
                    pass: process.env.EMAIL_PASS
                }
            });

            const mailOptions = {
                from: `"PriceBuddy Demo" <${process.env.EMAIL_USER}>`,
                to: product.user_email,
                subject: `📉 DEMO ALERT: ${product.name} Price Drop!`,
                html: `
                    <div style="font-family: sans-serif; padding: 20px; border: 1px solid #00E5FF; border-radius: 10px;">
                        <h1 style="color: #00E5FF;">DEMO PRICE DROP</h1>
                        <p>This is a simulated price drop for your demo.</p>
                        <p><strong>Product:</strong> ${product.name}</p>
                        <p><strong>New Price:</strong> <span style="color: #16a34a; font-size: 20px;">₹${newPrice.toLocaleString()}</span></p>
                        <p><strong>Previous:</strong> ₹${oldPrice.toLocaleString()}</p>
                        <p style="margin-top: 20px; font-size: 12px; color: #666;">Generated by the PriceBuddy Demo Script.</p>
                    </div>
                `
            };

            await transporter.sendMail(mailOptions);
            console.log(`🚀 Demo email sent to ${product.user_email}`);
        }

        console.log("\n✨ Demo complete! Refresh your dashboard now to see the changes.");

    } catch (error) {
        console.error("❌ Demo Error:", error.message);
    } finally {
        process.exit();
    }
}

simulatePriceUpdate();
